spring:
  application:
    name: K-API-Gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, kbws
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
server:
  port: 8090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: k-api-gateway
    qosPort: 33333
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

